spring:
    datasource:
        url: jdbc:h2:mem:coupondb
        driverClassName: org.h2.Driver
        username: coupon
        password:
    h2.console.enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true

#spring.h2.console.settings.trace=false
#spring.h2.console.settings.web-allow-others=false
